/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_rieon_tools_immanager_InputMethodManager */

#ifndef _Included_cn_rieon_tools_immanager_InputMethodManager
#define _Included_cn_rieon_tools_immanager_InputMethodManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_rieon_tools_immanager_InputMethodManager
 * Method:    getCurrentInputMethod
 * Signature: ()Lcn/rieon/tools/immanager/InputMethod;
 */
JNIEXPORT jobject JNICALL Java_cn_rieon_tools_immanager_InputMethodManager_getCurrentInputMethod
  (JNIEnv *, jclass);

/*
 * Class:     cn_rieon_tools_immanager_InputMethodManager
 * Method:    getAvailableInputMethods
 * Signature: ()[Lcn/rieon/tools/immanager/InputMethod;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_rieon_tools_immanager_InputMethodManager_getAvailableInputMethods
  (JNIEnv *, jclass);

/*
 * Class:     cn_rieon_tools_immanager_InputMethodManager
 * Method:    switchTo
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_rieon_tools_immanager_InputMethodManager_switchTo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_rieon_tools_immanager_InputMethodManager
 * Method:    getInputMethod
 * Signature: (Ljava/lang/String;)Lcn/rieon/tools/immanager/InputMethod;
 */
JNIEXPORT jobject JNICALL Java_cn_rieon_tools_immanager_InputMethodManager_getInputMethod
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
